# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly JAR Maven Plugin - CI

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  build:
    name: ${{ matrix.os }}-jdk${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest ]
        java: ['11']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build on ${{ matrix.java }}
        run: mvn clean install '-DskipTests' '-Dtest.jvm.args=-Dorg.wildfly.logging.skipLogManagerCheck=true' '-Dorg.wildfly.bootable.jar.ci.execution=true'
      - name: Test on ${{ matrix.java }}
        run: mvn install '-Dtest=org.wildfly.plugins.bootablejar.maven.goals.DevWatchTestCase' '-Dtest.jvm.args=-Dorg.wildfly.logging.skipLogManagerCheck=true' '-Dorg.wildfly.bootable.jar.ci.execution=true'
        working-directory: tests
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*.txt'
      #- uses: actions/upload-artifact@v2
      #  if: failure()
      #  with:
      #    name: artifacts-${{ matrix.os }}-${{ matrix.java }}
      #    path: '**/devwatch-watch-test/*'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*.txt'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: devwatch-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/dev-watch-test-output.txt'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/tests/**/logs/**'